## Config file for default TES fit in mutau channel
##

channel: mumu

#tag: "_mumu"
#tag: "_mumu_zptD"
#tag: "_mumu_zptDY"
#tag: "_mumu_zptDY_etacut"
#tag: "_mumu_trigger"
#tag: "_mumu_v10"
#tag: "_mumu_Dt2p5_2022"
#tag: "_mumu_Dt2p5_202-test"
tag: "_mumu_Dt2p5_puppiMET"


#baselineCuts: "q_1*q_2<0 && iso_1<0.15 && iso_2<0.15 && !lepton_vetoes && metfilter && eta_1<2.1 && eta_2<2.4"
baselineCuts: "q_1*q_2<0 && iso_1<0.15 && iso_2<0.15 && !lepton_vetoes && metfilter"


samples:
    filename: "$PICODIR/$SAMPLE_$CHANNEL$TAG.root"
    split:
        DY: [ ["ZTT","genmatch_2==5"], ["ZL","genmatch_2>0 && genmatch_2<5"], ["ZJ","genmatch_2==0"] ]
        #DY: [ ["ZLL","genmatch_2>0 && genmatch_2<5 && genmatch_1>0 && genmatch_1<5"], ["ZJ","genmatch_2==0"] ]
        #DY_M50: "ZLL"
    data: "data_obs"



# regions:
#     ZMM: 
#         definition: "true"

observables:
    m_vis:
        binning: [1, 70,  110]
        extra:
            ymargin: 1.6
            rrange: 0.08
        fitRegions: ["baseline"]

processes: ['ZTT','ZL','ZJ','data_obs'] #enlever les bruits de fond 

systematics:
    lumi:
        effect: "lnN"
        processes: ["ZTT","ZL","ZJ"]
        scaleFactor: 1.025
    eff_m:
        effect: "lnN"
        processes: ["ZTT","ZL","ZJ"]
        scaleFactor: 1.02