## Config file for default TES fit in mutau channel
##

channel: mumu

#tag: "_mumu"
#tag: "_mumu_zptD"
#tag: "_mumu_zptDY"
#tag: "_mumu_zptDY_etacut"
#tag: "_mumu_trigger"
#tag: "_mumu_v10"
tag: "_mumu_Dt2p5_202-test"


#baselineCuts: "q_1*q_2<0 && iso_1<0.15 && iso_2<0.15 && !lepton_vetoes && metfilter && eta_1<2.1 && eta_2<2.4"
baselineCuts: "q_1*q_2<0 && iso_1<0.15 && iso_2<0.15 && !lepton_vetoes && metfilter"


samples:
    filename: "$PICODIR/$SAMPLE_$CHANNEL$TAG.root"
    join: ["VV","TT","ST"]
    split:
        DY: [ ["ZTT","genmatch_2==5"], ["ZL","genmatch_2>0 && genmatch_2<5"], ["ZJ","genmatch_2==0"] ]
        #DY: [ ["ZLL","genmatch_2>0 && genmatch_2<5 && genmatch_1>0 && genmatch_1<5"], ["ZJ","genmatch_2==0"] ]
    rename:
        WJ: "W"
        #DY_M50: "ZLL"
    data: "data_obs"



# regions:
#     ZMM: 
#         definition: "true"

observables:
    m_vis:
        binning: [1, 70,  110]
        extra:
            ymargin: 1.6
            rrange: 0.08
        fitRegions: ["baseline"]

processes: ['ZTT','ZL','ZJ', 'W','VV','ST','TT','QCD','data_obs']

systematics:
    lumi:
        effect: "lnN"
        processes: ["ZTT","ZL","ZJ", "TT", "W", "ST", "VV"]
        scaleFactor: 1.025
    eff_m:
        effect: "lnN"
        processes: ["ZTT","ZL","ZJ","TT", "W", "ST", "VV"]
        scaleFactor: 1.02

# Additional scale factors per year for specific processes (correction of xsec, reco SFs, etc.)
scaleFactors:
  eff_m:
    processes: ['ZTT', 'ZL', 'ZJ', 'TTT', 'TTL', 'TTJ', 'W', 'ST', 'VV']
    values:
      {
      '': 1.00013301952,
      }
  lumi:
    processes: ['ZTT', 'ZL', 'ZJ', 'TTT', 'TTL', 'TTJ', 'W', 'ST', 'VV']
    values:
      {
      '': 1.00030709917,
      }
  xsec_dy:
    processes: ['ZTT','ZL','ZJ']
    values:
      {
      '': 0.973431169987,
      }