#
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional


# Typically, each channel will have its own config file; combination can be done at datacard level

channel: mutau

# Tag can be used to differentiate between scenarios

#tag: "_mtlt65_noSF_DMpt_mvisbin_10"
#tag: "_mtlt65_noSF_DMpt"
#tag: "_mtlt65_noSF_DMpt_mvisbin_50_rebin"
#tag: "_mtlt65_noSF_DMpt_mvisbin_200_rebin"
#tag: "_mtlt65_noSF_DMpt_mvisbinfullrange_10"
tag: "_mtlt65_noSF_DMpt_11bins"

baselineCuts: "q_1*q_2<0 && iso_1<0.15 && idDecayModeNewDMs_2 && idDeepTau2017v2p1VSjet_2>=32 && idDeepTau2017v2p1VSe_2>=2 && idDeepTau2017v2p1VSmu_2>=8 && !lepton_vetoes_notau && metfilter"

# These regions will be defined when creating inputs or making plots
# At this point, they do not need to be exclusive; 
# PLEASE NOTE:
#     - which regions are included in the fit will be defined in obervables section --> adjust when changing regions
#     - additional cross section scale factors applied to some processes need to be given in these regions to be considered --> adjust in scaleFactors section

regions:
    DM0_pt1: 
        definition: "mt_1<65 && dm_2==0 && pt_2>20 && pt_2<25"
        title: "h^{#pm}"
    DM1_pt1: 
        definition: "mt_1<65 && dm_2==1 && pt_2>20 && pt_2<25 "
        title: "h^{#pm}#pi^{0}"
    DM10_pt1: 
        definition: "mt_1<65 && dm_2==10 && pt_2>20 && pt_2<25"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11_pt1: 
        definition: "mt_1<65 && dm_2==11 && pt_2>20 && pt_2<25"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###
    DM0_pt2: 
        definition: "mt_1<65 && dm_2==0 && pt_2>25 && pt_2<30"
        title: "h^{#pm}"
    DM1_pt2: 
        definition: "mt_1<65 && dm_2==1 && pt_2>25 && pt_2<30"
        title: "h^{#pm}#pi^{0}"
    DM10_pt2: 
        definition: "mt_1<65 && dm_2==10 && pt_2>25 && pt_2<30"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11_pt2: 
        definition: "mt_1<65 && dm_2==11 && pt_2>25 && pt_2<30"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###
    DM0_pt3: 
        definition: "mt_1<65 && dm_2==0 && pt_2>30 && pt_2<35"
        title: "h^{#pm}"
    DM1_pt3: 
        definition: "mt_1<65 && dm_2==1 && pt_2>30 && pt_2<35"
        title: "h^{#pm}#pi^{0}"
    DM10_pt3: 
        definition: "mt_1<65 && dm_2==10 && pt_2>30 && pt_2<35"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11_pt3: 
        definition: "mt_1<65 && dm_2==11 && pt_2>30 && pt_2<35"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###
    DM0_pt4: 
        definition: "mt_1<65 && dm_2==0 && pt_2>35 && pt_2<40"
        title: "h^{#pm}"
    DM1_pt4: 
        definition: "mt_1<65 && dm_2==1 && pt_2>35 && pt_2<40"
        title: "h^{#pm}#pi^{0}"
    DM10_pt4: 
        definition: "mt_1<65 && dm_2==10 && pt_2>35 && pt_2<40"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11_pt4: 
        definition: "mt_1<65 && dm_2==11 && pt_2>35 && pt_2<40"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###
    DM0_pt5: 
        definition: "mt_1<65 && dm_2==0 && pt_2>40 && pt_2<50"
        title: "h^{#pm}"
    DM1_pt5: 
        definition: "mt_1<65 && dm_2==1 && pt_2>40 && pt_2<50"
        title: "h^{#pm}#pi^{0}"
    DM10_pt5: 
        definition: "mt_1<65 && dm_2==10 && pt_2>40 && pt_2<50"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11_pt5: 
        definition: "mt_1<65 && dm_2==11 && pt_2>40 && pt_2<50"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###
    DM0_pt6: 
        definition: "mt_1<65 && dm_2==0 && pt_2>50 && pt_2<70"
        title: "h^{#pm}"
    DM1_pt6: 
        definition: "mt_1<65 && dm_2==1 && pt_2>50 && pt_2<70"
        title: "h^{#pm}#pi^{0}"
    DM10_pt6: 
        definition: "mt_1<65 && dm_2==10 && pt_2>50 && pt_2<70"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11_pt6: 
        definition: "mt_1<65 && dm_2==11 && pt_2>50 && pt_2<70"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###
    DM0_pt7: 
        definition: "mt_1<65 && dm_2==0 && pt_2>70"
        title: "h^{#pm}"
    DM1_pt7: 
        definition: "mt_1<65 && dm_2==1 && pt_2>70"
        title: "h^{#pm}#pi^{0}"
    DM10_pt7: 
        definition: "mt_1<65 && dm_2==10 && pt_2>70"
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11_pt7: 
        definition: "mt_1<65 && dm_2==11 && pt_2>70"
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###

# #tes 
plottingOrder: ["DM11", "DM10","DM1", "DM0"]

# #tid SF
# plottingOrder: ["pt1", "pt2", "pt3", "pt4", "pt5", "pt6", "pt7"]

# Observable: to be fitted and plotted
# binning: as defined in TH1 (nbins, xmin, xmax)
# regions: (defined separately) to be included in the fit for this observable

tesRegions:
    DM0: 
        title: "h^{#pm}"
    DM1: 
        title: "h^{#pm}#pi^{0}"
    DM10: 
        title: "h^{#pm}h^{#mp}h^{#pm}"
    DM11: 
        title: "h^{#pm}h^{#mp}h^{#pm}#pi^{0}" ###

tid_SFRegions:
    pt1: 
        title: "20<p_{t_{#tau}}<25"
    pt2: 
        title: "25<p_{t_{#tau}}<30"
    pt3: 
        title: "30<p_{t_{#tau}}<35"
    pt4: 
        title: "35<p_{t_{#tau}}<40" ###
    pt5: 
        title: "40<p_{t_{#tau}}<50"
    pt6: 
        title: "50<p_{t_{#tau}}<70"
    pt7: 
        title: "70<p_{t_{#tau}}" ###


observables:
    m_vis:
        binning: [11, 50, 105]
        title: "m_{vis}"
        extra:
            cut: "10<m_vis && m_vis<106"
        fitRegions: ["DM0_pt1","DM0_pt2","DM0_pt3","DM0_pt4","DM0_pt5","DM0_pt6","DM0_pt7", "DM1_pt1","DM1_pt2","DM1_pt3","DM1_pt4","DM1_pt5","DM1_pt6","DM1_pt7","DM10_pt1","DM10_pt2","DM10_pt3","DM10_pt4","DM10_pt5","DM10_pt6","DM10_pt7","DM11_pt1","DM11_pt2","DM11_pt3","DM11_pt4","DM11_pt5","DM11_pt6","DM11_pt7"]
        #scanRegions: ["pt1", "pt2", "pt3", "pt4", "pt5", "pt6", "pt7"]
        scanRegions: ["DM0", "DM1", "DM10", "DM11"] 


# Assume that this code is meant to fit TES variations; more options could be added when adding other POIs

TESvariations:
    values: [0.970, 0.972, 0.974, 0.976, 0.978, 0.980, 0.982, 0.984, 0.986, 0.988, 0.990, 0.992, 0.994, 0.996, 0.998, 1.000, 1.002, 1.004, 1.006, 1.008, 1.010, 1.012, 1.014, 1.016, 1.018, 1.020, 1.022, 1.024, 1.026, 1.028, 1.030]
    #values: [0.970, 0.971, 0.972, 0.973, 0.974, 0.975, 0.976, 0.977, 0.978, 0.979, 0.980, 0.981, 0.982, 0.983, 0.984, 0.985, 0.986, 0.987, 0.988, 0.989,0.990, 0.991, 0.992, 0.993, 0.994, 0.995, 0.996, 0.997, 0.998, 0.999, 1.000, 1.001, 1.002, 1.003, 1.004, 1.005, 1.006, 1.007, 1.008, 1.009, 1.010, 1.011, 1.012, 1.013, 1.014, 1.015, 1.016, 1.017, 1.018, 1.019, 1.020, 1.021, 1.022, 1.023, 1.024, 1.025, 1.026, 1.027, 1.028, 1.029, 1.030]
    processes: ["ZTT"]

# Should add bin-by-bin variations (stat. uncertainties) for signal and backgrounds?

fitSpecs:
    doBBB: doShapes
    signalBBB: True
    backgroundBBB: True


# Samples to be used and association to processes entering analysis
# Possibility to remove or add specific weights / SFs from global weight

samples:
    filename: "$PICODIR/$SAMPLE_$CHANNEL$TAG.root"
    join: ["VV","TT","ST"]
    split:
        DY: [ ["ZTT","genmatch_2==5"], ["ZL","genmatch_2>0 && genmatch_2<5"], ["ZJ","genmatch_2==0"] ]
        TT: [["TTT","genmatch_2==5"], ["TTL","genmatch_2>0 && genmatch_2<5"], ["TTJ","genmatch_2==0"] ]
        #ST: [("STT","genmatch_2==5"),("STJ","genmatch_2<5")]
    rename:
        WJ: "W"
    data: "data_obs"
    removeSFs: ["idweight_2"]
    #addSFs: []


# Processes taken into account in analysis

processes: ["ZTT","ZL","ZJ","W","VV","ST","TTT","TTL","TTJ","QCD","data_obs"]

# Systematic uncertainties: can have effect shape or lnN (normalisation)

systematics:
    LTF:
        effect: "shape"
        processes: ["ZL", "TTL"]
        name: "shape_mTauFake_$BIN"
        title: "+/- 2% LTF shape"
        variations: ["Up", "Down"]
        sampleAppend: ["_LTFUp","_LTFDown"]
    JTF:
        effect: "shape"
        processes: ["ZJ", "TTJ", "W"]
        name: "shape_jTauFake_$BIN"
        title: "+/- 5% JTF"
        variations: ["Up", "Down"]
        sampleAppend: ["_JTFUp","_JTFDown"]
    shape_mTauFake:
        effect: "shape"
        processes: ["ZL", "TTL"]
        name: "shape_mTauFakeSF"
        title: "LTF rate syst"
        variations: ["Up", "Down"]
        nomWeight: "ltfweight_2"
        altWeights: ["ltfweightUp_2", "ltfweightDown_2"]
    shape_dy:
        effect: "shape"
        processes: ["ZTT", "ZL", "ZJ"]
        name: "shape_dy"
        title: "+/- 10% Zptweight"
        variations: ["Up", "Down"]
        nomWeight: "zptweight"
        altWeights: ["(zptweight+0.1*(zptweight-1))", "(zptweight-0.1*(zptweight-1))"]
    lumi:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ", "TTT", "TTL", "TTJ", "W", "ST", "VV"]
        scaleFactor: 1.025
    eff_m:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ", "TTT", "TTL", "TTJ", "W", "ST", "VV"]
        scaleFactor: 1.02
    xsec_dy:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ"]
        scaleFactor: 1.02
    xsec_tt:
        effect: "lnN"
        processes: ["TTT", "TTL", "TTJ"]
        scaleFactor: 1.06
    xsec_st:
        effect: "lnN"
        processes: ["ST"]
        scaleFactor: 1.05
    xsec_vv:
        effect: "lnN"
        processes: ["VV"]
        scaleFactor: 1.05
    norm_wj:
        effect: "lnN"
        processes: ["W"]
        scaleFactor: 1.08
    norm_qcd:
        effect: "lnN"
        processes: ["QCD"]
        scaleFactor: 1.10
    rate_jTauFake_$BIN:
        effect: "lnN"
        processes: ["W","QCD","ZJ","TTJ","STJ"]
        scaleFactor: 1.15

# Additional scale factors per year for specific processes (correction of xsec, reco SFs, etc.)

scaleFactors:
    WNFs:
        processes: ["W"]
        values:
            'UL2016_preVFP': { 'dm_2==0': 0.939,  'dm_2==1': 1.031,  'dm_2==10': 1.065,  'dm_2==11': 1.021  }
            'UL2016_postVFP': { 'dm_2==0': 0.919,  'dm_2==1': 0.972,  'dm_2==10': 1.112,  'dm_2==11': 1.074  }
            'UL2017': { 'dm_2==0': 0.971,  'dm_2==1': 0.995,  'dm_2==10': 1.109,  'dm_2==11': 1.075  }
            'UL2018': { 'dm_2==0': 1.007,  'dm_2==1': 0.968,  'dm_2==10': 1.079,  'dm_2==11': 1.044  }
